sudo: false
language: python
python:
  - "3.6"
install: pip install tox==3.3.0 tox-travis
script: tox
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
deploy:
  skip_cleanup: true
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASS
  distributions: bdist_wheel
  on:
    tags: true
